name: Continue On Error Demo

on:
  push:
    branches:
      -main

jobs:
  python-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run app.py
        run: python app.py
        continue-on-error: true

      - name: print success from workflow
        run: echo "workflow continued successfully."
    